### ISSUE TITLE
websocket always disconnect

### ISSUE THREAD

**Issue by thunderyan** [dushixiang/next-terminal#248]
next-terminal version:  dushixiang/next-terminal:v1.2.7 (v1.2.5)
guacd version: dushixiang/guacd:1.4.0
using docker and compose deploy

error:
`Session Manager 404cecf3-bdac-4fcf-b785-586e194a21d3  Open
{"time":"2022-04-22T20:21:00.8930444+08:00","level":"-","prefix":"echo","file":"recover.go","line":"109","message":"[PANIC RECOVER] concurrent write to websocket connection goroutine 2198 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1()\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/recover.go:89 +0x11a\npanic({0xcc3000, 0x15a5f90})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\ngithub.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000c68678, 0x1, {0xc000408f19?, 0xc000408f18?, 0x1?})\n\t/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x52b\ngithub.com/gorilla/websocket.(*Conn).WriteMessage(0xc00032e580, 0xdd9577?, {0xc000408f18, 0x1, 0x8})\n\t/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x139\nnext-terminal/server/api.WriteMessage(0xc00029a070?, {0xdcec2a?, {0x0?, 0xc00032e501?}})\n\t/app/server/api/term.go:275 +0x51\nnext-terminal/server/api.WebTerminalApi.SshEndpoint({}, {0x15b2ad8, 0xc00030e140})\n\t/app/server/api/term.go:205 +0x1714\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x15b2ad8, 0xc00030e140})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:520 +0x51\nnext-terminal/server/app.Auth.func1({0x15b2ad8, 0xc00030e140})\n\t/app/server/app/middleware.go:127 +0x456\nnext-terminal/server/app.TcpWall.func1({0x15b2ad8?, 0xc00030e140?})\n\t/app/server/app/middleware.go:39 +0xbc\nnext-terminal/server/app.ErrorHandler.func1({0x15b2ad8, 0xc00030e140})\n\t/app/server/app/middleware.go:21 +0x3f\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x15b2ad8, 0xc00030e140})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/cors.go:207 +0x8b8\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1({0x15b2ad8, 0xc00030e140})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/recover.go:115 +0xfe\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0004786c0, {0x15add88?, 0xc0001cc540}, 0xc00013c100)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:630 +0x3bc\nnet/http.serverHandler.ServeHTTP({0xc000fea510?}, {0x15add88, 0xc0001cc540}, 0xc00013c100)\n\t/usr/local/go/src/net/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc000638280, {0x15ae490, 0xc000117530})\n\t/usr/local/go/src/net/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3071 +0x4db\n\ngoroutine 1 [IO wait, 1 minutes]:\ninternal/poll.runtime_pollWait(0x7fee6dd69678, 0x72)\n\t/usr/local/go/src/runtime/netpoll.go:302 +0x89\ninternal/poll.(*pollDesc).wait(0xc00022c300?, 0xc0000021a0?, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:88\ninternal/poll.(*FD).Accept(0xc00022c300)\n\t/usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c\nnet.(*netFD).accept(0xc00022c300)\n\t/usr/local/go/src/net/fd_unix.go:172 +0x35\nnet.(*TCPListener).accept(0xc00047cd20)\n\t/usr/local/go/src/net/tcpsock_posix.go:139 +0x28\nnet.(*TCPListener).AcceptTCP(0xc00047cd20)\n\t/usr/local/go/src/net/tcpsock.go:275 +0x3d\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x43ec60?})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:939 +0x1d\nnet/http.(*Server).Serve(0xc0001da000, {0x15ad068, 0xc0007a0e80})\n\t/usr/local/go/src/net/http/server.go:3039 +0x385\ngithub.com/labstack/echo/v4.(*Echo).Start(0xc0004786c0, {0xc00003609c, 0xc})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:647 +0xce\nnext-terminal/server/app.Run()\n\t/app/server/app/app.go:130 +0x2ab\nmain.main()\n\t/app/main.go:10 +0x19\n\ngoroutine 6 [select, 54 minutes]:\ndatabase/sql.(*DB).connectionOpener(0xc0002a3450, {0x15ae3e8, 0xc0002f2d40})\n\t/usr/local/go/src/database/sql/sql.go:1226 +0x8d\ncreated by database/sql.OpenDB\n\t/usr/local/go/src/database/sql/sql.go:794 +0x18d\n\ngoroutine 81 [select, 5 minutes]:\ngithub.com/patrickmn/go-cache.(*janitor).Run(0xc000596000, 0x0?)\n\t/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x85\ncreated by github.com/patrickmn/go-cache.runJanitor\n\t/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xed\n\ngoroutine 97 [select, 5 minutes]:\ngithub.com/patrickmn/go-cache.(*janitor).Run(0xc0007a4000, 0x0?)\n\t/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1\n"}
echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
echo: http: response.Write on hijacked connection from github.com/labstack/echo/v4.(*Response).Write (response.go:75)
{"time":"2022-04-22T20:21:00.893318195+08:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"415","message":"http: connection has been hijacked"}`

PS: the server close WAN access, only can access the LAN network.

use the native method to access the SSH from next-terminal to target server.

**Comment by dushixiang** [comment]
已确认此问题，将在下一个版本进行修复。
