### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by zhaobzh** [dushixiang/next-terminal#266]
fatal error: concurrent map read and map write

goroutine 457 [running]:
runtime.throw({0xdd694e?, 0xc000c3dc38?})
        /usr/lib/go/src/runtime/panic.go:992 +0x71 fp=0xc000c3dc00 sp=0xc000c3dbd0 pc=0x433ff1
runtime.mapaccess1_faststr(0x544fd8?, 0xc00097aa00?, {0xc000c4c1e0, 0x24})
        /usr/lib/go/src/runtime/map_faststr.go:22 +0x3a5 fp=0xc000c3dc68 sp=0xc000c3dc00 pc=0x412925
next-terminal/server/global/gateway.Gateway.CloseSshTunnel({{0xc000c4dec0, 0x24}, 0x1, 0xc000a26b40, {0x0, 0x0}, 0xc000537350, 0xc0001152c0, 0xc000115320, 0xc000bfa930}, ...)
        /next-terminal-1.2.7/server/global/gateway/gateway.go:114 +0x53 fp=0xc000c3dd18 sp=0xc000c3dc68 pc=0xbbfa93
next-terminal/server/service.assetService.CheckStatus.func1()
        /next-terminal-1.2.7/server/service/asset.go:131 +0x45 fp=0xc000c3dd88 sp=0xc000c3dd18 pc=0xbef645
next-terminal/server/service.assetService.CheckStatus({{}}, {0xc0002464e0?, 0x0?}, {0xc00089b1d0?, 0xd?}, 0x0?)
        /next-terminal-1.2.7/server/service/asset.go:141 +0x25a fp=0xc000c3dec0 sp=0xc000c3dd88 pc=0xbef57a
next-terminal/server/service.CheckAssetStatusJob.Run.func1()
        /next-terminal-1.2.7/server/service/job_check_asset_status.go:49 +0x93 fp=0xc000c3dfe0 sp=0xc000c3dec0 pc=0xbf5b33
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c3dfe8 sp=0xc000c3dfe0 pc=0x463b21
created by next-terminal/server/service.CheckAssetStatusJob.Run
        /next-terminal-1.2.7/server/service/job_check_asset_status.go:42 +0x153

当启用计划任务中的资产状态检测，就会出现并发读写map的bug。我的资产列表中有大约137台资产

**Comment by dushixiang** [comment]
> fatal error: concurrent map read and map write
> 
> 
> 
> goroutine 457 [running]:
> 
> runtime.throw({0xdd694e?, 0xc000c3dc38?})
> 
>         /usr/lib/go/src/runtime/panic.go:992 +0x71 fp=0xc000c3dc00 sp=0xc000c3dbd0 pc=0x433ff1
> 
> runtime.mapaccess1_faststr(0x544fd8?, 0xc00097aa00?, {0xc000c4c1e0, 0x24})
> 
>         /usr/lib/go/src/runtime/map_faststr.go:22 +0x3a5 fp=0xc000c3dc68 sp=0xc000c3dc00 pc=0x412925
> 
> next-terminal/server/global/gateway.Gateway.CloseSshTunnel({{0xc000c4dec0, 0x24}, 0x1, 0xc000a26b40, {0x0, 0x0}, 0xc000537350, 0xc0001152c0, 0xc000115320, 0xc000bfa930}, ...)
> 
>         /next-terminal-1.2.7/server/global/gateway/gateway.go:114 +0x53 fp=0xc000c3dd18 sp=0xc000c3dc68 pc=0xbbfa93
> 
> next-terminal/server/service.assetService.CheckStatus.func1()
> 
>         /next-terminal-1.2.7/server/service/asset.go:131 +0x45 fp=0xc000c3dd88 sp=0xc000c3dd18 pc=0xbef645
> 
> next-terminal/server/service.assetService.CheckStatus({{}}, {0xc0002464e0?, 0x0?}, {0xc00089b1d0?, 0xd?}, 0x0?)
> 
>         /next-terminal-1.2.7/server/service/asset.go:141 +0x25a fp=0xc000c3dec0 sp=0xc000c3dd88 pc=0xbef57a
> 
> next-terminal/server/service.CheckAssetStatusJob.Run.func1()
> 
>         /next-terminal-1.2.7/server/service/job_check_asset_status.go:49 +0x93 fp=0xc000c3dfe0 sp=0xc000c3dec0 pc=0xbf5b33
> 
> runtime.goexit()
> 
>         /usr/lib/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c3dfe8 sp=0xc000c3dfe0 pc=0x463b21
> 
> created by next-terminal/server/service.CheckAssetStatusJob.Run
> 
>         /next-terminal-1.2.7/server/service/job_check_asset_status.go:42 +0x153
> 
> 
> 
> 
> 
> 当启用计划任务中的资产状态检测，就会出现并发读写map的bug。我的资产列表中有大约137台资产

收到，将在近期修复。
